"use client";

import { useState, useEffect } from "react";
import {
  useAccount,
  useContractWrite,
  useWaitForTransaction,
  useContractRead,
} from "wagmi";
// Use the ABI generated by deploy.js
import RealEstateNFTABI from "@/contracts/RealEstateNFT.json";
import contractAddresses from "@/contracts/addresses.json";
import "@/lib/buffer"; // Import Buffer polyfill
import { Dialog } from "@/components/ui/Dialog";
import { Button } from "@/components/ui/Button";

export default function NFTModal({ isOpen, onClose, addTransaction }) {
  const { address } = useAccount();
  const [formData, setFormData] = useState({
    name: "",
    description: "",
    location: "",
    price: "",
    currency: "AED", // Default currency is now AED
    sqft: "",
    bedrooms: "",
    bathrooms: "",
    yearBuilt: "",
    imageUrl: "",
  });

  // Reset form when modal is opened
  useEffect(() => {
    if (isOpen) {
      setFormData({
        name: "",
        description: "",
        location: "",
        price: "",
        currency: "AED",
        sqft: "",
        bedrooms: "",
        bathrooms: "",
        yearBuilt: "",
        imageUrl: "",
      });
    }
  }, [isOpen]);

  // Check if connected wallet is the contract owner
  const { data: contractOwner, isLoading: isLoadingOwner } = useContractRead({
    address: contractAddresses.RealEstateNFT,
    abi: RealEstateNFTABI,
    functionName: "owner",
  });

  const isContractOwner =
    contractOwner?.toLowerCase() === address?.toLowerCase();

  // Contract write hook for minting NFTs
  const {
    data: mintData,
    write: mint,
    isLoading: isMinting,
  } = useContractWrite({
    address: contractAddresses.RealEstateNFT,
    abi: RealEstateNFTABI,
    functionName: "mint",
    onSuccess: (data) => {
      console.log("Mint transaction successful:", data);
    },
    onError: (error) => {
      console.error("Mint transaction error:", error);
    },
  });

  // Wait for transaction hook
  const { isLoading: isWaitingForTx, isSuccess: isTxSuccess } =
    useWaitForTransaction({
      hash: mintData?.hash,
      onSuccess: (data) => {
        // Close modal on successful transaction
        onClose();
      },
    });

  // Handle form input changes
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      console.log("Minting NFT with data:", formData);
      console.log("Minting to address:", address);
      console.log("Contract address:", contractAddresses.RealEstateNFT);

      // Create metadata for the NFT
      const metadata = {
        name: formData.name,
        description: formData.description,
        image: formData.imageUrl,
        attributes: [
          { trait_type: "Location", value: formData.location },
          {
            trait_type: "Price",
            value: `${formData.price} ${formData.currency}`,
          },
          { trait_type: "Square Feet", value: formData.sqft },
          { trait_type: "Bedrooms", value: formData.bedrooms },
          { trait_type: "Bathrooms", value: formData.bathrooms },
          { trait_type: "Year Built", value: formData.yearBuilt },
        ],
      };

      // Convert metadata to JSON string
      const metadataStr = JSON.stringify(metadata);
      console.log("Metadata:", metadataStr);

      // Create a data URI
      const dataUri = `data:application/json;base64,${Buffer.from(
        metadataStr
      ).toString("base64")}`;
      console.log(
        "Data URI created (truncated):",
        dataUri.substring(0, 50) + "..."
      );

      // Call the mint function
      mint({
        args: [address, dataUri],
      });

      // Add transaction to log
      if (mintData?.hash) {
        addTransaction({
          hash: mintData.hash,
          description: `Minted NFT: ${formData.name}`,
        });
      }
    } catch (error) {
      console.error("Error minting NFT:", error);
    }
  };

  // Loading state
  const isLoading = isMinting || isWaitingForTx;

  return (
    <Dialog
      open={isOpen}
      onClose={onClose}
      title="Mint New Property NFT"
      preventClose={isLoading}
      className="max-w-4xl min-w-[400px] max-h-[90vh] overflow-y-auto"
    >
      {isContractOwner ? (
        <div className="mb-4 p-3 bg-green-100 text-green-800 rounded-md">
          <p className="font-medium">✓ You are the contract owner</p>
          <p className="text-sm">You can mint new NFTs.</p>
        </div>
      ) : (
        <div className="mb-4 p-3 bg-yellow-100 text-yellow-800 rounded-md">
          <p className="font-medium">⚠️ You are not the contract owner</p>
          <p className="text-sm">Connect with the admin wallet to mint NFTs.</p>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700">
              Property Name
            </label>
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded-md"
              placeholder="My Property"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">
              Location
            </label>
            <input
              type="text"
              name="location"
              value={formData.location}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded-md"
              placeholder="123 Main St, Anytown, USA"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">
              Price
            </label>
            <div className="flex">
              <input
                type="text"
                name="price"
                value={formData.price}
                onChange={handleChange}
                className="w-full p-2 border border-gray-300 rounded-l-md"
                placeholder="1,000,000"
              />
              <span className="inline-flex items-center px-3 border border-l-0 border-gray-300 bg-gray-50 text-gray-500 rounded-r-md">
                AED
              </span>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">
              Square Feet
            </label>
            <input
              type="number"
              name="sqft"
              value={formData.sqft}
              onChange={handleChange}
              required
              className="w-full p-2 border border-gray-300 rounded-md"
              placeholder="1200"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">
              Bedrooms
            </label>
            <input
              type="number"
              name="bedrooms"
              value={formData.bedrooms}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded-md"
              placeholder="2"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">
              Bathrooms
            </label>
            <input
              type="number"
              name="bathrooms"
              value={formData.bathrooms}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded-md"
              placeholder="2"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">
              Year Built
            </label>
            <input
              type="number"
              name="yearBuilt"
              value={formData.yearBuilt}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded-md"
              placeholder="2020"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">
              Image URL
            </label>
            <input
              type="text"
              name="imageUrl"
              value={formData.imageUrl}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded-md"
              placeholder="https://example.com/image.jpg"
            />
          </div>
        </div>

        <div className="flex justify-end mt-6 gap-4">
          <Button type="button" onClick={onClose} variant="secondary">
            Cancel
          </Button>
          <Button
            type="submit"
            disabled={!isContractOwner || isLoading}
            variant={!isContractOwner ? "secondary" : "primary"}
            className={
              !isContractOwner ? "opacity-50" : isLoading ? "opacity-75" : ""
            }
          >
            {isLoading ? "Minting..." : "Mint NFT"}
          </Button>
        </div>
      </form>
    </Dialog>
  );
}
